### ISSUE TITLE
SpaceX

### ISSUE THREAD

**Issue by petrosh** [petrosh/gitmarks#51]
![spacex-logo-4-702x143](https://cloud.githubusercontent.com/assets/4997583/17751515/b92f31cc-64c7-11e6-9e39-fab70651c84c.jpg)

- [From r/SpaceX](https://github.com/petrosh/gitmarks/issues/51#issuecomment-348700108)
- [FH](https://github.com/petrosh/gitmarks/issues/51#issuecomment-348700184)
- [Youtubes](https://github.com/petrosh/gitmarks/issues/51#issuecomment-290634887)

## External

- [SpaceX Presskits - Google Drive](https://drive.google.com/drive/folders/0B-b6nrwPXu05VVZpYTJfZVlrU0U)
- [ksc audio broadcast](http://audio2.broadcastify.com/ksc.mp3)

**Comment by petrosh** [comment]
# Youtubes

- [SES-10, ice](https://youtu.be/xfNO571C7Ko?t=2725)
- [YouTube - Live streams - List - Newest](https://www.youtube.com/user/spacexchannel/videos?view=2&flow=list)

**Comment by petrosh** [comment]
## Previsions

```yml
-
  date:
    declaration: 2017
    prevision:
      - 2020
      - 2021
  title: Manned dragon to ISS
  description: Will you ride Dragon to ISS?
  link: https://www.reddit.com/r/spacex/comments/6o947y/elon_musks_keynote_speech_at_the_2017_issrd/
-
  date:
    declaration: 2017
  title: Tunnels good for Mars
  description: Ice mining will be important, also underground habitats for radiation shielding. Entire cities underground if you wanted to.
  link: https://www.reddit.com/r/spacex/comments/6o947y/elon_musks_keynote_speech_at_the_2017_issrd/
```
